### ISSUE TITLE
name parsing errors

### ISSUE THREAD

**Issue by colindaven** [mmpust/raspir#17]
Hi @mmpust 

It might be sensible to put these parsing attempts in a try/ catch block to avoid common name errors. I'll have a go at a test and PR.

```
  File "raspir.py", line 175, in fourier_trans
    stripped_name2 = stripped_name[3] + ' ' + stripped_name[4]
IndexError: list index out of range
Traceback (most recent call last):
  File "raspir.py", line 351, in <module>
    main(args)
  File "raspir.py", line 347, in main
    process_csv(args.csv_file, out_prefix=args.out_prefix, args=args)
  File "raspir.py", line 322, in process_csv
    frequency_domain = frequency_domain0.groupby('Organism').apply(fourier_trans)
  File "/mnt/ngsnfs/tools/miniconda3/envs/raspir_env/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1272, in apply
    result = self._python_apply_general(f, self._selected_obj)
  File "/mnt/ngsnfs/tools/miniconda3/envs/raspir_env/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1306, in _python_apply_general
    keys, values, mutated = self.grouper.apply(f, data, self.axis)
  File "/mnt/ngsnfs/tools/miniconda3/envs/raspir_env/lib/python3.8/site-packages/pandas/core/groupby/ops.py", line 820, in apply
    res = f(group)
  File "raspir.py", line 175, in fourier_trans
    stripped_name2 = stripped_name[3] + ' ' + stripped_name[4]
IndexError: list index out of range
```

**Comment by colindaven** [comment]
https://github.com/mmpust/raspir/pull/18
