### ISSUE TITLE
TypeError: DataFrame.drop() takes from 1 to 2 positional arguments but 3 were given:

### ISSUE THREAD

**Issue by amitfenn** [mmpust/raspir#24]
Thank you Marie,
for this cool tool to identify rare species in metagenomic data. And for helping me already, to understand the potential of using it in our metagenomic data.

I have a challenge with running Raspir. Here are the outputs of the final command 

`python3 /lustre/groups/hpc/urban_lab/tools/raspir/run_raspir/raspir.py $csv_file ${csv_file%.csv}`

```
2023-11-13 16:31:18,137 - 1a) Human reads have been removed
2023-11-13 16:31:20,920 - 1b) Human chr reads have been removed
Traceback (most recent call last):
 File "/home/haicu/am*n/miniconda3/envs/raspir_env/lib/python3.12/site-packages/pandas/core/groupby/groupby.py", line 1766, in apply
   result = self._python_apply_general(f, self._selected_obj)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/haicu/am*n/miniconda3/envs/raspir_env/lib/python3.12/site-packages/pandas/core/groupby/groupby.py", line 1815, in _python_apply_general
   values, mutated = self.grouper.apply_groupwise(f, data, self.axis)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/haicu/am*n/miniconda3/envs/raspir_env/lib/python3.12/site-packages/pandas/core/groupby/ops.py", line 905, in apply_groupwise
   res = f(group)
         ^^^^^^^^
 File "/lustre*urban_lab/tools/raspir/run_raspir/raspir.py", line 85, in read_count
   x = x.drop(['items_diff', 'gap'], 1)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataFrame.drop() takes from 1 to 2 positional arguments but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/lustre*urban_lab/tools/raspir/run_raspir/raspir.py", line 376, in <module>
   main(args)
 File "/lustre*urban_lab/tools/raspir/run_raspir/raspir.py", line 372, in main
   process_csv(args.csv_file, out_prefix=args.out_prefix, args=args)
 File "/lustre*urban_lab/tools/raspir/run_raspir/raspir.py", line 327, in process_csv
   df_filter1 = df.groupby('Organism').apply(read_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/haicu/am*n/miniconda3/envs/raspir_env/lib/python3.12/site-packages/pandas/core/groupby/groupby.py", line 1776, in apply
   return self._python_apply_general(f, self._obj_with_exclusions)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/haicu/am*n/miniconda3/envs/raspir_env/lib/python3.12/site-packages/pandas/core/groupby/groupby.py", line 1815, in _python_apply_general
   values, mutated = self.grouper.apply_groupwise(f, data, self.axis)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/haicu/am*n/miniconda3/envs/raspir_env/lib/python3.12/site-packages/pandas/core/groupby/ops.py", line 905, in apply_groupwise
   res = f(group)
         ^^^^^^^^
 File "/lustre*urban_lab/tools/raspir/run_raspir/raspir.py", line 85, in read_count
   x = x.drop(['items_diff', 'gap'], 1)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataFrame.drop() takes from 1 to 2 positional arguments but 3 were given
/lustre*urban_lab/projects/amit/raspir/Greenhouse/hac1h/filtered_barcode14_passed.fastq.minimap2.sorted.raspir.csv
```

```
(base) [am*n@hpc slurm]$ head /lustre*urban_lab/projects/amit/raspir/Greenhouse/hac1h/filtered_barcode14_passed.fastq.minimap2.sorted.raspir.csv
GenomeLength,Organism,Position,Depth
2648638,1_AE000513_1_Deinococcus_radiodurans_R1_chromosome_1__complete_sequence_BAC,1711779,1
2648638,1_AE000513_1_Deinococcus_radiodurans_R1_chromosome_1__complete_sequence_BAC,1711780,1
2648638,1_AE000513_1_Deinococcus_radiodurans_R1_chromosome_1__complete_sequence_BAC,1711781,1
2648638,1_AE000513_1_Deinococcus_radiodurans_R1_chromosome_1__complete_sequence_BAC,1711782,1
2648638,1_AE000513_1_Deinococcus_radiodurans_R1_chromosome_1__complete_sequence_BAC,1711783,1
2648638,1_AE000513_1_Deinococcus_radiodurans_R1_chromosome_1__complete_sequence_BAC,1711784,1
2648638,1_AE000513_1_Deinococcus_radiodurans_R1_chromosome_1__complete_sequence_BAC,1711785,1
2648638,1_AE000513_1_Deinococcus_radiodurans_R1_chromosome_1__complete_sequence_BAC,1711786,1
2648638,1_AE000513_1_Deinococcus_radiodurans_R1_chromosome_1__complete_sequence_BAC,1711787,1
```

These are Oxford Nanopore Reads and the samfiles run here are from minimap. But I have also run the same on bowtie, and I get similar errors, can you help me please?

I would be happy to provide any additional details and my scripts, should it be needed.
Best wishes,
Amit.

**Comment by mmpust** [comment]
Hi Amit, the issue you're encountering with the drop() method in pandas might be due to changes in the pandas library version.  Can you try to change the 
```
 x = x.drop(['items_diff', 'gap'], 1)
```
in line 85 in your script "/lustre*urban_lab/tools/raspir/run_raspir/raspir.py" to
```
x = x.drop(labels=['items_diff', 'gap'], axis=1)
```
or equivalent to this:
```
x = x.drop(columns=['items_diff', 'gap'])
```
and see if that resolves the problem?
Best,
Marie

**Comment by amitfenn** [comment]
Thanks Marie, for your quick support and the easy fix.
Indeed, this was a small bug due to pandas,

**Comment by mmpust** [comment]
Great! Looking forward to hearing your experience with _raspir_ and nanopore data. Let me know if you need anything else!
